"""Common mapping dictionaries used across ETL pipelines."""

EMI_REGION_MAP = {
    "Taupo": "Waikato",
    "Marlborough": "Marlborough",
    "Thames Valley": "Waikato",
    "Ashburton": "Canterbury",
    "King Country": "Waikato",
    "Waitaki": "Canterbury",  # Could also be Otago, depending on boundary
    "Manawatu": "Manawatu",
    "Dunedin": "Otago",
    "Central Canterbury": "Canterbury",
    "North Canterbury": "Canterbury",
    "Central Otago": "Otago",
    "Counties": "Auckland",
    "Auckland": "Auckland",
    "Unknown": "Unknown",
    "Waikato": "Waikato",
    "Taranaki": "Taranaki",
    "Otago": "Otago",
    "Eastern Bay of Plenty": "Bay of Plenty",
    "Bay of Islands": "Northland",
    "Southland": "Southland",
    "Kapiti and Horowhenua": "Wellington",  # Could also be Manawatu
    "South Canterbury": "Canterbury",
    "Rotorua": "Bay of Plenty",
    "Tasman": "Tasman",
    "Tairawhiti and Wairoa": "Gisborne",  # Overlaps with northern Hawkes Bay
    "Southern Hawke's Bay": "Hawkes Bay",
    "Central Hawke's Bay": "Hawkes Bay",
    "Hawke's Bay": "Hawkes Bay",
    "Wellington": "Wellington",
    "Waipa": "Waikato",
    "Tauranga": "Bay of Plenty",
    "Wanganui": "Manawatu",
    "Whangarei and Kaipara": "Northland",
    "Buller": "West Coast",
    "Invercargill": "Southland",
    "Queenstown": "Otago",
    "West Coast": "West Coast",
    "Wairarapa": "Wellington",
    "Waitemata": "Auckland",
    "Nelson": "Nelson",
}
