"""Common mapping dictionaries used across ETL pipelines."""

EMI_REGION_MAP = {
    "Taupo": "Waikato",
    "Marlborough": "Marlborough",
    "Thames Valley": "Waikato",
    "Ashburton": "Canterbury",
    "King Country": "Waikato",
    "Waitaki": "Otago",
    "Manawatu": "Manawatu",
    "Dunedin": "Otago",
    "Central Canterbury": "Canterbury",
    "North Canterbury": "Canterbury",
    "Central Otago": "Otago",
    "Counties": "Auckland",
    "Auckland": "Auckland",
    "Unknown": "Unknown",
    "Waikato": "Waikato",
    "Taranaki": "Taranaki",
    "Otago": "Otago",
    "Eastern Bay of Plenty": "Bay of Plenty",
    "Bay of Islands": "Northland",
    "Southland": "Southland",
    "Kapiti and Horowhenua": "Wellington",  # Could also be Manawatu
    "South Canterbury": "Canterbury",
    "Rotorua": "Bay of Plenty",
    "Tasman": "Tasman",
    "Tairawhiti and Wairoa": "Gisborne",  # Overlaps with northern Hawkes Bay
    "Southern Hawke's Bay": "Hawkes Bay",
    "Central Hawke's Bay": "Hawkes Bay",
    "Hawke's Bay": "Hawkes Bay",
    "Wellington": "Wellington",
    "Waipa": "Waikato",
    "Tauranga": "Bay of Plenty",
    "Wanganui": "Manawatu",
    "Whangarei and Kaipara": "Northland",
    "Buller": "West Coast",
    "Invercargill": "Southland",
    "Queenstown": "Otago",
    "West Coast": "West Coast",
    "Wairarapa": "Wellington",
    "Waitemata": "Auckland",
    "Nelson": "Nelson",
}

EV_REGION_MAP = {
    "WHANGANUI DISTRICT": "Manawatu",
    "MANAWATU DISTRICT": "Manawatu",
    "PALMERSTON NORTH CITY": "Manawatu",
    "TARARUA DISTRICT": "Manawatu",
    "HOROWHENUA DISTRICT": "Manawatu",
    "RUAPEHU DISTRICT": "Manawatu",
    "GORE DISTRICT": "Southland",
    "SOUTHLAND DISTRICT": "Southland",
    "INVERCARGILL CITY": "Southland",
    "CENTRAL OTAGO DISTRICT": "Otago",
    "CLUTHA DISTRICT": "Otago",
    "DUNEDIN CITY": "Otago",
    "QUEENSTOWN-LAKES DISTRICT": "Otago",
    "AUCKLAND": "Auckland",
    "STRATFORD DISTRICT": "Taranaki",
    "NEW PLYMOUTH DISTRICT": "Taranaki",
    "SOUTH TARANAKI DISTRICT": "Taranaki",
    "HASTINGS DISTRICT": "Hawkes Bay",
    "NAPIER CITY": "Hawkes Bay",
    "RANGITIKEI DISTRICT": "Manawatu",
    "WAIROA DISTRICT": "Hawkes Bay",
    "CENTRAL HAWKE'S BAY DISTRICT": "Hawkes Bay",
    "WESTERN BAY OF PLENTY DISTRICT": "Bay of Plenty",
    "OPOTIKI DISTRICT": "Bay of Plenty",
    "WHAKATANE DISTRICT": "Bay of Plenty",
    "KAWERAU DISTRICT": "Bay of Plenty",
    "TAURANGA CITY": "Bay of Plenty",
    "WESTLAND DISTRICT": "West Coast",
    "GREY DISTRICT": "West Coast",
    "BULLER DISTRICT": "West Coast",
    "FAR NORTH DISTRICT": "Northland",
    "KAIPARA DISTRICT": "Northland",
    "WHANGAREI DISTRICT": "Northland",
    "TASMAN DISTRICT": "Tasman",
    "GISBORNE DISTRICT": "Gisborne",
    "MARLBOROUGH DISTRICT": "Marlborough",
    "WELLINGTON CITY": "Wellington",
    "CARTERTON DISTRICT": "Wellington",
    "MASTERTON DISTRICT": "Wellington",
    "KAPITI COAST DISTRICT": "Wellington",
    "SOUTH WAIRARAPA DISTRICT": "Wellington",
    "LOWER HUTT CITY": "Wellington",
    "UPPER HUTT CITY": "Wellington",
    "PORIRUA CITY": "Wellington",
    "WAIPA DISTRICT": "Waikato",
    "OTOROHANGA DISTRICT": "Waikato",
    "ROTORUA DISTRICT": "Bay of Plenty",
    "WAITOMO DISTRICT": "Waikato",
    "SOUTH WAIKATO DISTRICT": "Waikato",
    "MATAMATA-PIAKO DISTRICT": "Waikato",
    "HAMILTON CITY": "Waikato",
    "WAIKATO DISTRICT": "Waikato",
    "HAURAKI DISTRICT": "Waikato",
    "TAUPO DISTRICT": "Waikato",
    "THAMES-COROMANDEL DISTRICT": "Waikato",
    "KAIKOURA DISTRICT": "Canterbury",
    "ASHBURTON DISTRICT": "Canterbury",
    "WAIMAKARIRI DISTRICT": "Canterbury",
    "MACKENZIE DISTRICT": "Canterbury",
    "HURUNUI DISTRICT": "Canterbury",
    "CHRISTCHURCH CITY": "Canterbury",
    "WAIMATE DISTRICT": "Canterbury",
    "WAITAKI DISTRICT": "Canterbury",
    "SELWYN DISTRICT": "Canterbury",
    "TIMARU DISTRICT": "Canterbury",
    "NELSON CITY": "Nelson",
    "CHATHAM ISLANDS TERRITORY": "Southland",
    "UNKNOWN": "Unknown",
}
